# Generated by Django 3.1.1 on 2021-01-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
        ('pontos_turisticos', '0003_pontoturistico_atracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='comments',
            field=models.ManyToManyField(to='comment.Comentario'),
        ),
    ]
